services:
  whatsapp:
    image: aldinokemal2104/go-whatsapp-web-multidevice
    restart: always
    ports:
      - 3000 # Or "3000:3000" if you want a fixed host port
    volumes:
      - whatsapp__storage:/app/storages
    environment:
      - APP_BASIC_AUTH=${APP_BASIC_AUTH}
      - APP_PORT=${APP_PORT}
      - APP_DEBUG=${APP_DEBUG}
      - APP_OS=${APP_OS}
      - APP_ACCOUNT_VALIDATION=${APP_ACCOUNT_VALIDATION}
    networks: # <--- Add this section
      - dokploy-network # <--- Connect to the external network

volumes:
  whatsapp__storage:

networks:
  dokploy-network:
    external: true
