services:
  whatsapp:
    image: aldinokemal2104/go-whatsapp-web-multidevice
    container_name: whatsapp
    restart: always
    ports:
      - 3000
    volumes:
      - whatsapp:/app/storages
    environment:
      - APP_BASIC_AUTH=${APP_BASIC_AUTH}
      - APP_PORT=${APP_PORT}
      - APP_DEBUG=${APP_DEBUG}
      - APP_OS=${APP_OS}
      - APP_ACCOUNT_VALIDATION=${APP_ACCOUNT_VALIDATION}

volumes:
  whatsapp:
networks:
  dokploy-network:
    external: true
